### ISSUE TITLE
Theme check issues fixed

### ISSUE THREAD

**Issue by WPDevHQ** [kresogalic8/pixie#2]
Hello @kresogalic8 Krešo,

There were a number of issues that returned Warnings plus Theme check plugin requirements which are now fixed - see last section of the readme.txt file.

I've sent a PR as mentioned on Facebook and hope you will approve and merge the changes. You can compare with my fork here: https://github.com/WPDevHQ/pixie

Regards,
Zulf

**Comment by WPDevHQ** [comment]
P.S. I should also mention that I unminified the styles in style.css as this will make it easier for other to locate elements for modifications/additions :)

**Comment by kresogalic8** [comment]
Hello @WPDevHQ i will check all and pull it. I really appreciate what you added. 

One thing about style.css, u don't need to unminified, there is gulp task which can define that - now is compressed but it can be expanded or compact style.

**Comment by WPDevHQ** [comment]
I was thinking more of those that don't use or are unable to use gulp :)
